<?php
include('../strade.php');
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-08-05 at 20:49:18.
 */
abstract class stradeTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var strade
     */
    protected $strade;

    protected $message='Custom unicode message ółść';


    /**
     * @covers smstrade::send
     */
    public function testSend()
    {
        $o=&$this->strade;
        $o->setDebug(true);
        $mid=$o->send('4912312312311',$this->message);
        $this->assertEquals('123456789',$mid);
    }


    /**
     * @covers smstrade::senderror
     */
    public function testSendError()
    {
        try {
            $o=&$this->strade;
            $o->setDebug(true);
            $o->send('x',$this->message);
        } catch (StradeException $e) {
            $this->assertNotEmpty($e->getMessage());
        }
    }
}
